repo_url: https://github.com/Requisitos-de-Software/2025.1-e-GDF
repo_name: 2025.1-e-GDF

site_name: e-GDF

nav:
  - Home: index.md
  - Apresentação: 
    - Apresentação 1: apresentacoes/apresentacao.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
    - Apresentação 4: apresentacoes/apresentacao4.md
    - Apresentação 6: apresentacoes/apresentacao6.md
    - Apresentação 5: apresentacoes/apresentacao5.md


  - Atas:
    - Ata 1: atas/ata01.md
    - Ata 2: atas/ata02.md
    - Ata 3: atas/ata03.md
    - Ata 4: atas/ata04.md
    - Ata da inspeção da entrega 1: atas/ata_inspecao1.md
    - Ata 5: atas/ata05.md
    - Ata 6: atas/ata06.md
    - Ata 7: atas/ata07.md
    - Ata 8: atas/ata08.md
    - Ata 9: atas/ata9.md
    - Ata 10: atas/ata10.md
    - Ata 11: atas/ata11.md
  - Pré-Rastreabilidade: 
    - Rich Picture: pre-rastreabilidade/rich_picture.md
  - Planejamento:
    - Aplicativos Selecionados: planejamento/aplicativos_selecionados.md
    - Aplicativo Escolhido: planejamento/app_selecionado.md
    - Ferramentas: planejamento/ferramentas.md
    - Heat Map: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Metodologia: planejamento/metodologia.md
    - Termo de Uso: planejamento/termos_de_uso.md
  - Elicitação:
    - Técnicas:
      - Analise de Documentos: elicitacao/tec_elicitacao/analise_documentos.md
      - Brainstorming: elicitacao/tec_elicitacao/brainstorming.md
      - Entrevista: elicitacao/tec_elicitacao/entrevista.md
      - Introspecção: elicitacao/tec_elicitacao/introspeccao.md
    - Priorização:
      - First Things First: elicitacao/tec_priorizacao/first_things_first.md
      - Moscow: elicitacao/tec_priorizacao/moscow.md
      - ROI: elicitacao/tec_priorizacao/roi.md
      - 100: elicitacao/tec_priorizacao/100.md
    - Requisitos Elicitados: elicitacao/req_elicitados.md
    - Perfil de Usuário: elicitacao/perfil_de_usuario.md
  - Modelagem:
      - Cenários: modelagem/cenario.md
      - Léxicos:  modelagem/lexico.md
      - Casos de Uso: modelagem/casos_de_uso.md
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Ágil:
          - NFR Framework: modelagem/agil/nfrframework.md
          - Backlog: modelagem/agil/backlog.md
          - Histórias de Usuário: modelagem/agil/historia-de-usuario.md    
  - Rastreabilidade:
      - Matriz de Rastreabilidade: rastreabilidade/matriz_rastreabilidade.md  
      - Forward From: rastreabilidade/forward_from.md   
      - Backward From: rastreabilidade/backward_from.md 
  - Validação:
      - Prototipação: validacao/prototipacao.md
      - Comprovação Informal: validacao/comprovacao.md
  - Entrega-final:
    - Aplicativos Selecionados: entrega-final/aplicativo-selecionado.md
    - Artefatos Criados: entrega-final/artefatos-criados.md
    - Execução do Projeto: entrega-final/execucao-projeto.md
    - Ferramentas Utilizadas: entrega-final/ferramentas-utilizadas.md
    - Resultados Alcançados: entrega-final/resultados-alcancados.md
    - Tabela de Apresentações: entrega-final/tabela-apresentacoes.md
    - Técnicas utilizadas: entrega-final/tecnicas-utilizadas.md
    - Planejamento dos Recursos e das entregas: entrega-final/panejamento-recursos.md
    - Verificação: entrega-final/verificacao.md   
    - Validação: entrega-final/validacao.md
    - Considerações Finais: entrega-final/consideracoes-finais.md       
      

  - Verificação:
      - Avaliação -1: verificacao/grupo/avaliacao-1.md
      - Grupo:
          - Entrega 1: verificacao/grupo/entrega01/entrega01grupo.md
          - Entrega 2: verificacao/grupo/entrega02/entrega02grupo.md
          - Entrega 3: verificacao/grupo/entrega03/entrega03grupo.md
          - Entrega 4: verificacao/grupo/entrega04/entrega04grupo.md
          - Entrega 5: verificacao/grupo/entrega05/entrega05grupo.md
          - Entrega 6: verificacao/grupo/entrega06/entrega06grupo.md
      - Grupo +1:
          - Entrega 1: verificacao/grupo/entrega01/entrega01grupo+1.md
          - Entrega 2: verificacao/grupo/entrega02/entrega02grupo+1.md
          - Entrega 3: verificacao/grupo/entrega03/entrega03grupo+1.md
          - Entrega 4: verificacao/grupo/entrega04/entrega04grupo+1.md
          - Entrega 5: verificacao/grupo/entrega05/entrega05grupo+1.md
          - Entrega 6: verificacao/grupo/entrega06/entrega06grupo+1.md
  - Inspeção:
      - Grupo:
          - Entrega 1: inspecao/inspecao_1_grupo.md
          - Entrega 2: inspecao/inspecao_2_grupo.md
          - Entrega 3: inspecao/inspecao_3_grupo.md
          - Entrega 4: inspecao/inspecao_4_grupo.md
          - Entrega 5: inspecao/inspecao_6_grupo.md
          - Entrega 6: inspecao/inspecao_5_grupo.md
      - Grupo +1:
          - Entrega 1: inspecao/inspecao_1_grupo+1.md
          - Entrega 2: inspecao/inspecao_2_grupo+1.md
          - Entrega 3: inspecao/inspecao_3_grupo+1.md
          - Entrega 4: inspecao/inspecao_4_grupo+1.md
          - Entrega 5: inspecao/inspecao_6_grupo+1.md
          - Entrega 6: inspecao/inspecao_5_grupo+1.md


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Claro

  language: pt-BR
  favicon: assets/egdf_logo.png
  logo: assets/egdf_logo.png

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details

plugins:
  - glightbox:
      touchNavigation: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      caption_position: bottom